// Generated by gencpp from file tweaked_keyboard_teleop/Sound.msg
// DO NOT EDIT!


#ifndef TWEAKED_KEYBOARD_TELEOP_MESSAGE_SOUND_H
#define TWEAKED_KEYBOARD_TELEOP_MESSAGE_SOUND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tweaked_keyboard_teleop
{
template <class ContainerAllocator>
struct Sound_
{
  typedef Sound_<ContainerAllocator> Type;

  Sound_()
    : sound(0)  {
    }
  Sound_(const ContainerAllocator& _alloc)
    : sound(0)  {
  (void)_alloc;
    }



   typedef uint8_t _sound_type;
  _sound_type sound;




  typedef boost::shared_ptr< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> const> ConstPtr;

}; // struct Sound_

typedef ::tweaked_keyboard_teleop::Sound_<std::allocator<void> > Sound;

typedef boost::shared_ptr< ::tweaked_keyboard_teleop::Sound > SoundPtr;
typedef boost::shared_ptr< ::tweaked_keyboard_teleop::Sound const> SoundConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tweaked_keyboard_teleop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tweaked_keyboard_teleop': ['/home/bot/catkin_ws/src/tweaked_keyboard_teleop/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e311aa13fbaf5cd07833ae9e8811de43";
  }

  static const char* value(const ::tweaked_keyboard_teleop::Sound_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe311aa13fbaf5cd0ULL;
  static const uint64_t static_value2 = 0x7833ae9e8811de43ULL;
};

template<class ContainerAllocator>
struct DataType< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tweaked_keyboard_teleop/Sound";
  }

  static const char* value(const ::tweaked_keyboard_teleop::Sound_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 sound\n\
";
  }

  static const char* value(const ::tweaked_keyboard_teleop::Sound_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sound);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sound_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tweaked_keyboard_teleop::Sound_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tweaked_keyboard_teleop::Sound_<ContainerAllocator>& v)
  {
    s << indent << "sound: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sound);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWEAKED_KEYBOARD_TELEOP_MESSAGE_SOUND_H
